site_name: Combine
repo_name: GitHub
repo_url: https://github.com/cms-analysis/HiggsAnalysis-CombinedLimit
edit_uri: edit/main/docs

nav:
        - Home: index.md
        - What Combine Does:
            - Introduction: what_combine_does/introduction.md
            - Model and Likelihood: what_combine_does/model_and_likelihood.md
            - Fitting Concepts: what_combine_does/fitting_concepts.md
            - Statistical Tests: what_combine_does/statistical_tests.md
        - Setting Up the Analysis:
          - "Preparing the Datacard": part2/settinguptheanalysis.md
          - "Physics Models":
              - "Introduction": part2/physicsmodels.md
              - "SM Higgs Coupling Models": part2/higgscouplings.md
              - "BSM Higgs Models": part2/bsm-higgs-models.md
          - "Automatic MC Statistical Uncertainties": part2/bin-wise-stats.md
        - Running Combine:
          - "Running the Tool":           part3/runningthetool.md
          - "Common Statistical Methods": part3/commonstatsmethods.md
          - "Advanced Use Cases":         part3/nonstandard.md
          - "Simplified Likelihoods":     part3/simplifiedlikelihood.md
          - "Unfolding & Regularization": part3/regularisation.md
          - "Validating Datacards":       part3/validation.md
          - "Debugging Fit Failures":     part3/debugging.md
        - Tutorials:
          - "RooFit Basics":              part5/roofit.md
          - "Main Features":
            - "Exercises":                part5/longexercise.md
            - "Solutions":                part5/longexerciseanswers.md
          - "Parametric Models":          tutorial2023/parametric_exercise.md
          - "Likelihood-Based Unfolding": tutorial2023_unfolding/unfolding_exercise.md
          - "Statistical Tests Basics":   tutorial_stat_routines/stat_routines.md
          - "Model Building":             model_building_tutorial2024/model_building_exercise.md
          - "Per-Bin Transfer Factors with Parametric Histograms": abcd_rooparametrichist_tutorial/rooparametrichist_exercise.md
        - "In-Browser Tools":
          - "In-Browser Tools":           part6/in_browser_tools.md
          - "Open: jsROOT (external)":     https://root.cern/js/latest/
          - "Open: Datacard Viewer":       part6/view_datacard.html
          - "Open: Covariance Viewer":     part6/view_cov_json.html
        - Links & FAQ: part4/usefullinks.md

theme:
        name: material
        logo: logo.png
        favicon: logo.png
        custom_dir: docs/overrides
        features:
            - content.code.copy
            - navigation.footer
            - navigation.indexes
            - navigation.expand
            - navigation.tracking
            - navigation.tabs
            - navigation.tabs.sticky
            - navigation.top
            - search.highlight
            - search.suggest
            - toc.follow

plugins:
    - mike
    - search

extra:
    version:
        provider: mike

extra_css:
  - "mystyle.css"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill-fastly.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.blocks.details
  - admonition

