name: Run test in CVMFS environment
description: Execute a shell script inside an LCG or CMSSW environment sourced with CVMFS
inputs:
  script:
    description: Shell commands to execute after setup
    required: true

runs:
  using: "composite"
  steps:
    # Case 1: Run inside a Docker container if image is provided and assume CMSSW
    - name: Run command inside container
      if: ${{ env.IMAGE != '' }}
      uses: rhaschke/docker-run-action@v5
      with:
        image: ${{ env.IMAGE }}
        shell: bash
        options: -v /cvmfs:/cvmfs:shared -v cmsusr:/home/cmsusr/cmssw/:ro -v ${{ github.workspace }}:/workspace:rw -w /home/cmsusr/ -e CMSSW_VERSION=${{ env.CMSSW_VERSION }}
        run: >-
          cp -r cmssw/${CMSSW_VERSION} .;
          cd /home/cmsusr/${CMSSW_VERSION}/src;
          source /cvmfs/cms.cern.ch/cmsset_default.sh;
          cmsenv;
          ulimit -s unlimited;
          cd HiggsAnalysis/CombinedLimit;
          ${{ inputs.script }}
          # Copy outputs (if they exist) to /tmp for extraction
          if [ -d outputs ]; then
            mkdir -p /tmp/outputs
            cp -r outputs/* /tmp/outputs/ || true
          fi

    # Copy results back on the host
    - name: Copy outputs from container
      if: ${{ env.IMAGE != '' && always()}}
      shell: bash
      run: |
        docker_id=$(docker ps -alq)
        mkdir -p outputs
        docker cp "$docker_id":/tmp/outputs ./ || echo "No outputs to copy."

    # Case 2: Run directly on the GitHub runner if no image is provided and assume LCG
    - name: Run command on host
      if: ${{ env.IMAGE == '' }}
      shell: bash
      run: >-
        source /cvmfs/sft.cern.ch/lcg/views/${LCG_RELEASE}/${LCG_ARCH}/setup.sh;
        source virtualenv/bin/activate;
        export PATH=$PWD/install/bin:$PATH;
        export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH;
        ulimit -s unlimited;
        ${{ inputs.script }}
